
version: 2

sources:
    - name: staging
      tags: ["Source"]
      description : "bank_marketing"
      database: applied-well-362908
      schema : bank_marketing2
      tables:
        - name: bank_2022-10-01
        - name: bank_2022-10-02
        - name: bank_2022-10-03
        - name: bank_2022-10-04
        - name: bank_2022-10-05
        - name: bank_2022-10-06
        - name: bank_2022-10-07
        - name: bank_2022-10-08
        - name: bank_2022-10-09
        - name: bank_2022-10-10
        - name: bank_2022-10-11
        - name: bank_2022-10-12
        - name: bank_2022-10-13
        - name: bank_2022-10-14
        - name: bank_2022-10-15
        - name: bank_2022-10-16
        - name: bank_2022-10-17
        - name: bank_2022-10-18
        - name: bank_2022-10-19
        - name: bank_2022-10-20
        - name: bank_2022-10-21
        - name: bank_2022-10-22
        - name: bank_2022-10-23
        - name: bank_2022-10-24
        - name: bank_2022-10-25
        - name: bank_2022-10-26
        - name: bank_2022-10-27
        - name: bank_2022-10-28
        - name: bank_2022-10-29
        - name: bank_2022-10-30
        - name: bank_2022-10-31
        - name: bank_2022-11-01
        - name: bank_2022-11-02
        - name: bank_2022-11-03
        - name: bank_2022-11-04
        - name: bank_2022-11-05
        - name: bank_2022-11-06
        - name: bank_2022-11-07
        - name: bank_2022-11-08
        - name: bank_2022-11-09
        - name: bank_2022-11-10
        - name: bank_2022-11-11

models:
    - name: source_table
      description: This is source table
      columns:
        - name: id
          test:
            - not_null